{% set name = "imantics" %}
{% set version = "0.1.12" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2f806b158821a58a5b35014aecca4f7f853445bc304f847cef04dd0d8e05bd90
  patches:
    - change_cv2_and_opencv-python_to_py-opencv.patch

build: 
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python
    - lxml
    - numpy
    - opencv >=3
    - sphinx_rtd_theme

test:
  imports:
    - imantics

about:
  home: "https://github.com/jsbroks/imantics"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE"
  summary: "Python package for managing image annotations"
  doc_url: "https://pypi.org/project/imantics/"
  dev_url: "https://github.com/jsbroks/imantics"

extra:
  recipe-maintainers:
    - oblute
    - mwilson8
